### ISSUE TITLE
单页面单个图表数据及动画效果可渲染出来，但单页面内多个图表数据和动画效果渲染不出来

### ISSUE THREAD

**Issue by ahuihuihuihui0326** [VisActor/VChart#1333]
在使用vchart的时候，同一页面内，单个图表的动画效果（播放器）和数据渲染的没有任何问题，但同一页面内，多个图表，有些数据渲染不出来，有些图标的引导线后的名称渲染不出来，动画效果渲染的达不到单页面但图表的预期。且页面内有报错。
![693718bfdccd5c6bdcbbb891f23851a](https://github.com/VisActor/VChart/assets/149071370/7569215e-194d-4504-a570-a20d22b7c0c1)

**Comment by pairone** [comment]
The label text of the pie chart is not displayed. This may be because the text color is black by default, which is difficult to display on a dark background. You can try configuring the text color of the label to white. Refer to this link https://www.visactor.io/ vchart/option/pieChart#label.style.fill

-------------------------

饼图的标签文字未显示出来，可能是由于文字颜色是默认黑色的，在暗色背景下不易显示，可以尝试配置下label的文本颜色为白色，参考这个链接 https://www.visactor.io/vchart/option/pieChart#label.style.fill
