### ISSUE TITLE
[Demo] add demo of a bar chart

### ISSUE THREAD

**Issue by xile611** [VisActor/VChart#2658]
1.  实现条形图
<img width="1115" alt="image" src="https://github.com/VisActor/VChart/assets/6111424/76f9f124-e866-4d22-bb92-a4343cd20cab">

2. 交互细节如下：

<img width="424" alt="image" src="https://github.com/VisActor/VChart/assets/6111424/eef2b149-e4bd-47ee-a827-697180c33123">
<img width="1111" alt="image" src="https://github.com/VisActor/VChart/assets/6111424/ca828ea8-a6ce-43aa-b7a3-f47f01e92e93">

demo中用到的数据参考如下：

```
[{
        "x": "北京",
        "y": 3080,
        "type": "top1"
    }, {
        "x": "天津",
        "y": 2880,
        "type": "top2"
    }, {
        "x": "重庆",
        "y": 880,
        "type": "top3"
    }, {
        "x": "深圳",
        "y": 780,
        "type": "common"
    }, {
        "x": "广州",
        "y": 680,
        "type": "common"
    }, {
        "x": "山东",
        "y": 580,
        "type": "common"
    }, {
        "x": "浙江",
        "y": 480,
        "type": "common"
    }, {
        "x": "福建",
        "y": 100,
        "type": "common"
    }, {
        "x": "石家庄",
        "y": 100,
        "type": "common"
    }, {
        "x": "广西壮族自治区",
        "y": 100,
        "type": "common"
    }]
```

**Comment by Crayon-ShinChan** [comment]
I tried to use `barChart.label.customLayoutFunc` to position the label 

but it threw the error `TypeError: getRelatedGraphic is not a function` after I defined the function

```javascript
const layout = (data, getRelatedGraphic) => {
  // Find the maximum value of the bars
  const maxValue = Math.max(...data.map(d => d.value));

  return data.map(d => {
    // Find the graphic related to the current data point
    const baseMark = getRelatedGraphic(d);
    
    ...
 ```

**Comment by xile611** [comment]
@xiaoluoHe some bug happens in label component.

**Comment by xiaoluoHe** [comment]
@Crayon-ShinChan `getRelatedGraphic` is  at the third position in the parameters of `customLayoutFunc`.
You can refer to the code below. (Besides, the use of `customLayoutFunc` is more advanced; you might also consider implementing it through customMark or extensionMark.)
```
  label:{
    visible: true,
    overlap:false,
    customLayoutFunc: (attribute, text, f)=>{
        return text.map((t) => {
          const barRect = f(t.attribute);
          if(barRect){
            const y = Math.abs(barRect.AABBBounds.y1+barRect.AABBBounds.y2)/2;
            //Think about how to obtain the value of 𝑥
            t.setAttributes({x:100,y})
          }
          return t;
        })
    }
  },
```
![image](https://github.com/VisActor/VChart/assets/11360419/43fb882f-e113-45f4-9fec-793d3e6f77d9)

**Comment by Crayon-ShinChan** [comment]
> @Crayon-ShinChan `getRelatedGraphic` is at the third position in the parameters of `customLayoutFunc`.

Thanks for timely reply! https://www.visactor.io/vchart/option/barChart#label.customLayoutFunc may have the outdated statement that
```
函数回调参数为：(data: LabelItem[], getRelatedGraphic: (data: LabelItem) => IGraphic) => Text[]; 使用方式例如：
```
I may update that after I finish this issue.

**Comment by Crayon-ShinChan** [comment]
I implemented this chart in a tricky manner. I will provide a detailed explanation of my implementation and suggest some additional work that may be necessary to replace this tricky method.

# Problem we met

We want to position the label numbers to the right of the chart. It seems that using the `customLayoutFunc` function from the Label is the most natural approach to achieve this. From what I understand, if we were to use Mark for this, we might have to hard-code all the numbers, which is not ideal.

Therefore, I used `customLayoutFunc` in the way that @xiaoluoHe suggested. I encountered another problem when I did that. The label can not be positioned outside the axis range. (see the following image)
![CleanShot 2024-05-30 at 12 14 09@2x](https://github.com/VisActor/VChart/assets/38809606/d238afa8-719b-4e61-ab99-0a83320135a0)
As you can see, the numbers `3080` and `2880` were shifted to the left instead of remaining at `x = maxX2 - 15` because their length exceeded the right boundary of the X-axis. The other numbers could remain at `x = maxX2 - 15` because their widths were smaller. 

This means we can't put the label numbers to the right and out of the X axis if we set `nice: true` for the X axis.

# Tricky solution I used

## How to do

Because label numbers have to stay within X axis, so I

1. Removed `nice: true` for X axis, and set X axis to `max: 3500` which is larger than max x value, i.e. `3080`
2. Set `barBackground` to `scaleX: 3080 / 3500`. This prevented grey bar background from being longer than the longest bar, i.e. the bar for "北京" (I know it's hardcoded, but it's necessary in this case.)
3. Set x for labels as `maxX2 + 30` where `maxX2` is `Math.max(...attribute.map(attr => getRelatedGraphic(attr).AABBBounds.x2));`

Here is the result:

https://github.com/VisActor/VChart/assets/38809606/04e52e9d-5ae4-44aa-861f-7eaf60801508

## Limitation 

Because we kept `(1 - 3080/3500) * X-axis-width` for the label numbers, these labels would be pushed back to left when the width of the browser was very small. But it worked well when screen width was large enough.

# Further work to replace this tricky solution

## Allow the label to be positioned outside of the axis range.

All of the methods and limitations mentioned above stem from the inability to position labels outside of the range at the moment. Therefore, the most direct solution is to enable this feature.

## Use right axes to replace labels (Tableau style solution)

In Tableau, we are allowed to have multiple layers of an axis and put them into different sides of the chart.

For example, the following chart has `year` and `type` as X axis and put them in bottom and top separately:
![CleanShot 2024-05-30 at 15 40 58@2x](https://github.com/VisActor/VChart/assets/38809606/c75549a1-5057-42ea-b085-8a45c0e49c8e)

Similarly, we can have Y axis which is composed of `province` and `value`, put the `province` on the left and the `value` on the right, then we get the chart we want.

I've tried this solution with the following spec:

```javascript
const spec = {
  ...,
  yField: ['province', 'value'],
  seriesField: 'province',
  axes: [
    {
      orient: 'bottom',
      nice: true,
      max: 3500,
      visible: false
    },
    {
      orient: 'left',
      showAllGroupLayers: true,
      layers: [
        {
          visible: false
        },
        {
          visible: true
        }
      ],
      maxWidth: 65,
      label: {
        autoLimit: true
      },
      domainLine: {
        visible: false
      },
      tick: {
        visible: false
      }
    },
    {
      orient: 'right',
      showAllGroupLayers: true,
      layers: [
        {
          visible: true
        },
        {
          visible: false
        }
      ],
      domainLine: {
        visible: false
      },
      tick: {
        visible: false
      }
    }
  ],
  barBackground: {
    visible: true,
    style: {
      cornerRadius: [5, 5, 5, 5],
      // scaleX: 3080 / 3500,
      height: 10
    }
  },
  ...
};
```

Here is the result:
![CleanShot 2024-05-30 at 15 46 35@2x](https://github.com/VisActor/VChart/assets/38809606/db2a828e-a1c6-40a8-84c1-5ead2b9812f5)

As we can see, the issue we are facing is an of unnecessary bar backgrounds overlapping with each other, and the right axis does not display the correct numbers (always 3080 and 580).

The cause of this problem is that we can't hide some values in the second layer of y axis which has no value. 

Specifically, if we have the data
| Left y-axis, the 1st layer | Right y-axis, the 2nd layer | value |
| :--: |  :--: |  :--: |
| 北京 | 3080 | 3080 |
| 北京 | 2880 | NaN |
| 天津 | 3080 | NaN |
| 天津 | 2880 | 2880 |

I checked the document and it appears that VChart cannot hide the second and third rows with NaN values in the chart. This resulted in the problematic chart as shown above.

The solution is to allow us to hide the item in the second layer which has no value, i.e. only render the chart with the data like:

| Left y-axis, the 1st layer | Right y-axis, the 2nd layer | value |
| :--: |  :--: |  :--: |
| 北京 | 3080 | 3080 |
| 天津 | 2880 | 2880 |

**I highly recommend allowing this because data analysts frequently utilize multiple layers of axes (like those who use Tableau). This provides a lot of flexibility, which is not only beneficial for the current issue we are discussing but also proves extremely useful in other visualization scenarios.** I hope we can be as powerful as Tableau.

# What we need to do next?

1. I will create a pull request with the tricky solution to this issue, and it works almost perfectly.
2. We may discuss the further work stated above later as well

**Comment by xiaoluoHe** [comment]
@Crayon-ShinChan Thank you for such thoughtful and insightful comments.

Hard-coded logic can create difficulties for other users in terms of understanding and usage.

I have reservations about the statement "label numbers have to stay within the X axis."
If we disregard this constraint and think outside the box, using the capability of extensionMarks might solve the hard-coded issue. 
Perhaps you could refer to this [example](https://visactor.io/vchart/demo/custom/series-extension).

**Comment by FunctionEurus** [comment]
Hello, I got a equivlence for this (seemingly). However, it's still got a few drawbacks. Hope this helps!
```
const values = [
  {
    "x": "北京",
    "y": 3080,
    "type": "top1"
  }, {
    "x": "天津",
    "y": 2880,
    "type": "top2"
  }, {
    "x": "重庆",
    "y": 880,
    "type": "top3"
  }, {
    "x": "深圳",
    "y": 780,
    "type": "common"
  }, {
    "x": "广州",
    "y": 680,
    "type": "common"
  }, {
    "x": "山东",
    "y": 580,
    "type": "common"
  }, {
    "x": "浙江",
    "y": 480,
    "type": "common"
  }, {
    "x": "福建",
    "y": 100,
    "type": "common"
  }, {
    "x": "石家庄",
    "y": 100,
    "type": "common"
  }, {
    "x": "广西壮族自治区",
    "y": 100,
    "type": "common"
  }];

const max_y = Math.max(...values.map(el => el.y));

const spec = {
  type: 'bar',
  data: [
    {
      id: 'id0',
      values: values.map(el => ({ ...el, y: el.y / max_y }))
    }
  ],
  direction: 'horizontal',
  xField: 'y',
  yField: 'x',
  seriesField: 'type',
  cornerRadius: 20,
  bandWidth: 30,
  tooltip: {
    mark: {
      title: {
        visible: false
      },
      content: {
        key: datum => datum.x,
        value: datum => (datum.y * max_y).toFixed()
      }
    },
    dimension: {
      visible: false
      // title: {
      //   visible: false
      // },
      // content: {
      //   key: datum => datum.x,
      //   value: datum => (datum.y * max_y).toFixed()
      // }
    }
  },
  bar: {
    style: {
      cornerRadius: [5, 5, 5, 5],
      height: 10
    }
  },
  barBackground: {
    visible: true,
    style: {
      cornerRadius: [5, 5, 5, 5],
      height: 10
    }
  },
  axes: [
    {
      orient: 'left',
      label: {
        visible: true,
        style: {
          maxLineWidth: 50,
          // textAlign: 'start'
        },
      },
      type: 'band',
      domainLine: { visible: false },
      tick: { visible: true }
    },
    {
      orient: 'right',
      label: {
        visible: true,
        formatMethod: datum => values.find(el => el.x === datum).y,
      },
      type: 'band',
      domainLine: { visible: false },
      visible: true
    },
    {
      orient: 'bottom',
      visible: false
    },
  ]
};

const vchart = new VChart(spec, { dom: CONTAINER_ID });
vchart.renderSync();

// Just for the convenience of console debugging, DO NOT COPY!
window['vchart'] = vchart;
```
![1](https://github.com/VisActor/VChart/assets/104673088/69aa1075-584f-4884-84eb-fc47885f26b1)

**Comment by Crayon-ShinChan** [comment]
> Hello, I got a equivlence for this (seemingly). However, it's still got a few drawbacks. Hope this helps!
> 
> ```
> const values = [
>   {
>     "x": "北京",
>     "y": 3080,
>     "type": "top1"
>   }, {
>     "x": "天津",
>     "y": 2880,
>     "type": "top2"
>   }, {
>     "x": "重庆",
>     "y": 880,
>     "type": "top3"
>   }, {
>     "x": "深圳",
>     "y": 780,
>     "type": "common"
>   }, {
>     "x": "广州",
>     "y": 680,
>     "type": "common"
>   }, {
>     "x": "山东",
>     "y": 580,
>     "type": "common"
>   }, {
>     "x": "浙江",
>     "y": 480,
>     "type": "common"
>   }, {
>     "x": "福建",
>     "y": 100,
>     "type": "common"
>   }, {
>     "x": "石家庄",
>     "y": 100,
>     "type": "common"
>   }, {
>     "x": "广西壮族自治区",
>     "y": 100,
>     "type": "common"
>   }];
> 
> const max_y = Math.max(...values.map(el => el.y));
> 
> const spec = {
>   type: 'bar',
>   data: [
>     {
>       id: 'id0',
>       values: values.map(el => ({ ...el, y: el.y / max_y }))
>     }
>   ],
>   direction: 'horizontal',
>   xField: 'y',
>   yField: 'x',
>   seriesField: 'type',
>   cornerRadius: 20,
>   bandWidth: 30,
>   tooltip: {
>     mark: {
>       title: {
>         visible: false
>       },
>       content: {
>         key: datum => datum.x,
>         value: datum => (datum.y * max_y).toFixed()
>       }
>     },
>     dimension: {
>       visible: false
>       // title: {
>       //   visible: false
>       // },
>       // content: {
>       //   key: datum => datum.x,
>       //   value: datum => (datum.y * max_y).toFixed()
>       // }
>     }
>   },
>   bar: {
>     style: {
>       cornerRadius: [5, 5, 5, 5],
>       height: 10
>     }
>   },
>   barBackground: {
>     visible: true,
>     style: {
>       cornerRadius: [5, 5, 5, 5],
>       height: 10
>     }
>   },
>   axes: [
>     {
>       orient: 'left',
>       label: {
>         visible: true,
>         style: {
>           maxLineWidth: 50,
>           // textAlign: 'start'
>         },
>       },
>       type: 'band',
>       domainLine: { visible: false },
>       tick: { visible: true }
>     },
>     {
>       orient: 'right',
>       label: {
>         visible: true,
>         formatMethod: datum => values.find(el => el.x === datum).y,
>       },
>       type: 'band',
>       domainLine: { visible: false },
>       visible: true
>     },
>     {
>       orient: 'bottom',
>       visible: false
>     },
>   ]
> };
> 
> const vchart = new VChart(spec, { dom: CONTAINER_ID });
> vchart.renderSync();
> 
> // Just for the convenience of console debugging, DO NOT COPY!
> window['vchart'] = vchart;
> ```
> 
> ![1](https://private-user-images.githubusercontent.com/104673088/335507497-69aa1075-584f-4884-84eb-fc47885f26b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDg0NDIsIm5iZiI6MTcxNzE0ODE0MiwicGF0aCI6Ii8xMDQ2NzMwODgvMzM1NTA3NDk3LTY5YWExMDc1LTU4NGYtNDg4NC04NGViLWZjNDc4ODVmMjZiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwOTM1NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzU2NWZhMzVkOWQxYzc1MWYyYjc5YWViMjE4NTE5OWQwZjQ4YTc3OWI2OGZjN2NkNmFjODViNzU3NjZmYzY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L4TBb7YxKADCNOkBSvwRvQQlk5OVGweb9x073Ff48TE) Also I have a small question, why dont use linear progress chart?

Your solution is the extension of Tableau style solution. Good for you! The `formatMethod` you used to solve the problem with multiple layers of y-axes was done in a tricky and effective manner.

I like it! As I mentioned in the previous replies, adding two y-axes on the left and right can elegantly solve our problem without the need for additional layout functions.

Thank you!

**Comment by Crayon-ShinChan** [comment]
> @Crayon-ShinChan Thank you for such thoughtful and insightful comments.
> 
> Hard-coded logic can create difficulties for other users in terms of understanding and usage.
> 
> I have reservations about the statement "label numbers have to stay within the X axis." If we disregard this constraint and think outside the box, using the capability of extensionMarks might solve the hard-coded issue. Perhaps you could refer to this [example](https://visactor.io/vchart/demo/custom/series-extension).

I've updated the PR and discussed the two proposed solutions, i.e. axes and extensionMark solutions, in that PR.

For the statement "label numbers have to stay within the X axis." Check this example:
![image](https://github.com/VisActor/VChart/assets/38809606/7a8eb994-3482-42cb-ad74-901a04fe9564)

I set the x as `maxX2 - 15` with `nice: false`. As you can see, `3080` and `2880` are too long for the space I retained by `-15`, but all other numbers like `100` are short enough for this space. Therefore, `3080` and `2880` are pushed to the left which is equality of `inside` of the bar, especially for number on the second bar, `2880`.

This means when the label is outside of X axis range, `barChart.label.customLayoutFunc` won't take any effect. So in this case, we can say "label numbers have to stay within the X axis."
