### ISSUE TITLE
[demo] linear progress can not group correctly

### ISSUE THREAD

**Issue by kkxxkk2019** [VisActor/VChart#47]
![Image](https://user-images.githubusercontent.com/135952300/246762200-72118d11-7852-42b4-b1e9-a84132ca3ae0.png)

**Comment by pairone** [comment]
6.28 

Discussed with Zhang Hong an alternative to datadraw that does not take effect in groupMark: 

- generate multiple groupMarks from data after compile

6.29

code verification

**Comment by pairone** [comment]
This method ‘generate multiple groupMarks from data after compile’ doesn't work😭 

Because the number of scenes cannot be constructed

After discussing with Zhang Hong and Zhang Su, I decided to abandon the groupMark.

In VRender, can the rectMark of the background bar and the rectMark of the progress bar be used as clips? I throw this question to Xinyu：

'Can the rectMark support clip?'


Currently, concrete implementations to solve this problem are not well designed

**Comment by pairone** [comment]
- Use several rect arrays with the same shape as the track as the path of one groupMark

risk:
groupMark不支持path
![image](https://github.com/VisActor/VChart/assets/40026218/d07810d0-2a56-4f54-97b0-59d11b4d913c)

**Comment by pairone** [comment]
complete
![img_v2_c1e21808-4dc8-41fa-8c19-bfc46ef8bbag](https://github.com/VisActor/VChart/assets/40026218/09b2cc0c-9542-4169-b8a7-519d90a00bbf)
![img_v2_48120d16-a864-4f41-ae21-55fd6e4365dg](https://github.com/VisActor/VChart/assets/40026218/d519bca3-6bf0-43f5-aa1f-a591fb4255f4)
