### ISSUE TITLE
请指定容器或渲染画布

### ISSUE THREAD

**Issue by xyovo** [VisActor/VChart#568]
我在React中想使用VChart，在控制台却报错`Uncaught Error: please specify container or renderCanvas!`，请问这是什么原因导致的呢？下面是我的代码
---
（I want to use VChart in React, but I'm getting an error in the console: Uncaught Error: please specify container or renderCanvas! What could be causing this? Here is my code:）

```
import VChart from '@visactor/vchart';
export default function App() {
  const spec = {
    type: 'line',
    data: {
      values: [
        {
          time: '2:00',
          value: 8,
        },
        {
          time: '4:00',
          value: 9,
        },
        {
          time: '6:00',
          value: 11,
        },
        {
          time: '8:00',
          value: 14,
        },
        {
          time: '10:00',
          value: 16,
        },
        {
          time: '12:00',
          value: 17,
        },
        {
          time: '14:00',
          value: 17,
        },
        {
          time: '16:00',
          value: 16,
        },
        {
          time: '18:00',
          value: 15,
        },
      ],
    },
    xField: 'time',
    yField: 'value',
  };

  const vchart = new VChart(spec, { dom: 'chart' });
  vchart.renderAsync();

  return <div id='chart' style={{ width: 600, height: 400 }}></div>;
}

```

**Comment by xuanhun** [comment]
I suggest using the @visactor/react-vchart component. You can refer to the tutorial at https://visactor.io/vchart/guide/tutorial_docs/Cross-terminal_and_Developer_Ecology/react for more information.

建议你使用 @visactor/react-vchart 组件，教程参考https://visactor.io/vchart/guide/tutorial_docs/Cross-terminal_and_Developer_Ecology/react. @xyovo

**Comment by purpose233** [comment]
This error is due to the incorrect invocation time of vchart rendering. When `vchart.renderAsync` is written in synchronous code inside a react element, the rendering process of vchart will be executed before the container dom is created because of the react rendering logic.
The solution is to use `useRef` and `useEffect` hook to guarantee that when vchart renders the container dom exists.
Please refer to this [sample](https://codesandbox.io/p/sandbox/elegant-banzai-773kg4?file=/src/chart.tsx:7,53).

---

这个报错是由不正确的 VChart 调用时机导致的。如果在同步代码中调用 `vchart.renderAsync`，由于 react 的渲染逻辑，vchart 的渲染流程会在 container dom 创建之前执行。
解决方案是通过 `useRef` 和 `useEffect` 来保证 vchart 渲染时 container dom 已经存在。
可以参考这个 [示例](https://codesandbox.io/p/sandbox/elegant-banzai-773kg4?file=/src/chart.tsx:7,53)。

**Comment by xyovo** [comment]
> 

非常感谢，成功解决~
