### ISSUE TITLE
[FAQ]How to customize the axis label display spacing?

### ISSUE THREAD

**Issue by pairone** [VisActor/VChart#756]
A line chart like (https://visactor.io/vchart/demo/line-chart/basic-line),
![image](https://github.com/VisActor/VChart/assets/40026218/4ac9344b-f488-42ed-9cb7-76376e9be4f8)
How to realize the display spacing of custom axis labels?

**Comment by xuanhun** [comment]
## Solution



The solution varies depending on the chart library being used. Based on the provided demo, you simply need to set the corresponding field to false in order to disable stacking.

-   ` MinGap  `can be used to customize the minimum spacing between labels (unit: pixels). Only takes effect when axis sampling starts (`sampling: true`). This configuration affects the results of axis sampling.


  [![enter image description here][1]][1]


  


##  Code Example

```
const spec = {
  type: 'line',
  data: {
    values: [
      {
        time: '2:00',
        value: 8
      },
      {
        time: '4:00',
        value: 9
      },
      {
        time: '6:00',
        value: 11
      },
      {
        time: '8:00',
        value: 14
      },
      {
        time: '10:00',
        value: 16
      },
      {
        time: '12:00',
        value: 17
      },
      {
        time: '14:00',
        value: 17
      },
      {
        time: '16:00',
        value: 16
      },
      {
        time: '18:00',
        value: 15
      }
    ]
  },
  xField: 'time',
  yField: 'value',
  axes: [{
      orient: "bottom",
      label: {
          minGap: 80
      }
  }]
};
```

##  Results



Online demo：https://codesandbox.io/s/customize-axis-label-spacing-9ml6nv

[![!\[\](https://tech-proxy.bytedance.net/tos/images/1693820633887_96bb7699ccc43c4b101a99986cda02a6)][2]][2]

##  Related Documentation


Basic Line Chart Demo：https://www.visactor.io/vchart/demo/line-chart/basic-line

Line Chart Tutorial：https://www.visactor.io/vchart/guide/tutorial_docs/Chart_Types/Line

Related api：https://www.visactor.io/vchart/option/lineChart#axes-band.label.minGap

github：https://github.com/VisActor/VChart


  [1]: https://i.stack.imgur.com/mCBf9.png
  [2]: https://i.stack.imgur.com/TOBGE.png
