### ISSUE TITLE
[FAQ] How to configure the axis scale alignment of a two-axis graph?

### ISSUE THREAD

**Issue by ssfxz** [VisActor/VChart#795]
### What problem does this feature solve?

When I use the VChart chart, may I ask whether the data around the two horizontal coordinates can be aligned? The effect is equivalent to two axes overlapping.

### What does the proposed API look like?

![1280X1280 (1)](https://github.com/VisActor/VChart/assets/8744196/201b3242-b51a-4533-aab7-8bcf06d468cb)

**Comment by xuanhun** [comment]
## 解决方案 Solution

VChart中提供了这样的配置，如果你需要同步轴的范围使0值对齐，可以参考文档中的配置：https://visactor.io/vchart/option/barChart#axes-linear.sync.axisId

通过sync指定右轴向左轴对齐即可。需要注意的是：需要为左轴定义id，以便能够在其他轴中指定它。

  


VChart provided in this configuration. If you need synchronized axis alignment to 0, it can be configured in the reference documentation: https://visactor.io/vchart/option/barChart#axes-linear.sync.axisId

Use sync to specify the right axis and left axis alignment. Note that you need to define an id for the left axis so that you can specify it in the other axes.

  


## 代码示例 Code Example

```
spec.axes = [{
    orient: 'left',
    id: 'left_axis',
    seriesIndex: [0],
  },
  {
    orient: 'right',
    seriesId: ['line'],
    gird: {
      visible: false,
    },
    sync: {
      axisId: 'left_axis',
      zeroAlign: true
    }
  },
```

  


## 结果展示 Results

![image](https://github.com/VisActor/VChart/assets/2384516/77eb2bc7-0d27-4d36-bc8c-e9d50a4034b0)

Demo: https://codesandbox.io/s/dual-axis-zero-align-9y49w3?file=/src/index.ts

  


## 相关文档 Quote

Axis option：https://visactor.io/vchart/option/barChart#axes-linear.sync.axisId

github：https://github.com/VisActor/VChart
