### ISSUE TITLE
[FAQ] How to add background color to the bottom of ring chart when it is set with gaps?

### ISSUE THREAD

**Issue by FlyingAndFly** [VisActor/VChart#837]
In the design, there is a gap set between each piece of the ring chart, and there is also a gray background ring under the interval. How can this effect be achieved?
<div style="display:inline-block">
  <img src="https://github.com/VisActor/VChart/assets/143593654/d3c965aa-e799-4d7e-b6a8-aff2e2f203f2" alt="image1" width="300">
  <img src="https://github.com/VisActor/VChart/assets/143593654/1c3538d1-1223-405f-a6d0-eeded7e0aed3" alt="image2" width="300">
</div>

**Comment by xuanhun** [comment]
## 解决方案 Solution

这个效果可以用 VChart 的组合图实现。组合图可以配置两个饼图系列，第一个只有一条数据，用于模拟背景的环形；第二个系列就是常规的饼图系列。需要注意：

-   `padAngle`：配置间隔的角度；
-   `innerRadius`/`outerRadius`：配置内外半径。两个系列需要配置相同的内外半径；
-   系列之间的顺序不要颠倒，因为后配置的系列层级更高；
-   背景系列建议关闭动画 和 tooltip 交互；

  


This effect can be achieved using the common chart of VChart. The common chart can be configured with two pie series, where the first series has only one data to simulate the background ring, and the second series is a regular pie series. Note:

-   `padAngle`: Configure the angle of the interval;
-   `innerRadius`/`outerRadius`: Configure the inner and outer radius. Both series need to have the same inner and outer radius;
-   Do not reverse the order of the series between each other, because the series configured later has a higher z-index;
-   It is recommended to turn off animation and tooltip interaction for the background series.

![image](https://github.com/VisActor/VChart/assets/2384516/ca799c14-5554-40ee-925b-abe6a267650d)

代码参考：

```
const spec = {
  type: 'common',
  data: [
    {
      id: 'id0',
      values: [
        { type: '0~9', value: '39.12' },
        { type: '10~19', value: '43.01' },
        { type: '20~29', value: '43.91' },
        { type: '30~39', value: '45.4' },
        { type: '40~49', value: '40.89' },
        { type: '50~59', value: '42.48' },
        { type: '60~69', value: '39.63' },
        { type: '70~79', value: '25.17' },
        { type: '80 and over', value: '12.29' }
      ]
    },
    {
      id: 'id1',
      values: [
        { type: '0~9', value: '1' },
      ]
    }
  ],
  series: [
    {
      type: 'pie',
      id: 'background',
      dataIndex: 1,
      outerRadius: 0.8,
      innerRadius: 0.67,
      valueField: 'value',
      categoryField: 'type',
      animation: false,
      tooltip: { visible: false },
      pie: {
        style: {
          fill: 'rgb(237,239,242)',
        }
      }
    },
    {
      type: 'pie',
      dataIndex: 0,
      outerRadius: 0.8,
      innerRadius: 0.67,
      valueField: 'value',
      padAngle: 2,
      categoryField: 'type',
      pie: {
        style: {
          cornerRadius: 20,
        },
        state: {
          hover: {
            outerRadius: 0.82,
            innerRadius: 0.65,
          }
        }
      }
    }
  ],
  title: {
    visible: true,
    text: 'Population Distribution by Age in the United States, 2021 (in millions)',
    textStyle: {
      fontFamily: 'Times New Roman'
    }
  },
  legends: {
    visible: true,
    orient: 'left',
    seriesIndex: [1]
  }
};
```

  


## 结果展示 Results

在线效果参考：https://codesandbox.io/s/pie-background-with-padangle-365zgm

Online demo：https://codesandbox.io/s/pie-background-with-padangle-365zgm

  

![image](https://github.com/VisActor/VChart/assets/2384516/5130d964-6dae-438b-8f26-1a2222bdc9f9)


## 相关文档 Related Documentation

相关教程：https://visactor.io/vchart/guide/tutorial_docs/Chart_Types/Combination

相关 demo：https://visactor.io/vchart/demo/pie-chart/nested-pie?keyword=pieChart

github：https://github.com/VisActor/VChart

  


related tutorial：https://visactor.io/vchart/guide/tutorial_docs/Chart_Types/Combination

related demo：https://visactor.io/vchart/demo/pie-chart/nested-pie?keyword=pieChart

github：https://github.com/VisActor/VChart
