### ISSUE TITLE
[FAQ] How to combine percentage bar and TGI chart?

### ISSUE THREAD

**Issue by da730** [VisActor/VChart#877]
As shown in the following figure, I would like to use a front-end chart library to implement a combination of percentage bar chart and TGI chart:
![image](https://github.com/VisActor/VChart/assets/20367445/beea3ed3-0487-40b8-b843-c7b773dc9c5b)

The TGI chart uses vertical bars to represent TGI values and connects different bars with lines. As the two charts use different axes, how can we implement this?

**Comment by xuanhun** [comment]
## 解决方案 Solution

你可以使用@VisActor/VChart实现想要的效果。VChart允许多个series组合在一张图表中，仅需要将图表类型设为common，并在series中添加柱状图和折线图的series，修改折线图的线样式为虚线，点样式为矩形，即可实现图中效果。为了实现柱图与线图使用不同的坐标轴，在axes中，需要配置3个坐标轴：左侧的band轴，底部线图的linear轴，除此之外还需要给柱图配置一个linear轴。你可以将该轴放置在顶部并将visible设为false，并通过调整max属性，指定轴的范围，实现图中的效果。

You can use @VisActor/VChart to achieve the desired effect. VChart allows multiple series to be combined in one chart. You only need to set the chart type to "common" and add bar chart and line chart series in the series. Modify the line style of the line chart to dashed line and the point style to rectangle to achieve the effect in the figure. In order to use different coordinate axes for the bar chart and line chart, three coordinate axes need to be configured in the "axes": a left band axis, a bottom linear axis for the line chart, and a linear axis for the bar chart. You can place the bar chart axis at the top and set "visible" to false. By adjusting the "max" property, you can specify the range of the axis to achieve the effect in the figure.

## 代码示例 Code Example

图表spec如下：

The spec is as follows:

```
{
  type: 'common',
  data: [ { "id": "data", 
      "values": [ { "x": "2015-09-24", "y": 0.6 }, { "x": "2015-09-25", "y": 0.7 }, { "x": "2015-09-26", "y": 0.71 }, { "x": "2015-09-27", "y": 0.65 }, { "x": "2015-09-28", "y": 0.53 }, { "x": "2015-09-29", "y": 0.55 } ]},
 { "id": "data2", 
      "values":  [ { "x": "2015-09-24", "y": 40 }, { "x": "2015-09-25", "y": 25 }, { "x": "2015-09-26", "y": 31 }, { "x": "2015-09-27", "y": 37 }, { "x": "2015-09-28", "y": 28 }, { "x": "2015-09-29", "y": 22 } ] }       
      ],

  series: [
    {
      type: 'bar',
      id:'barSeries',
      direction:'horizontal',
      dataId:'data',
      yField: 'x',
      xField: 'y',
    },
    {
      type: 'line',
      id:'lineSeries',
      direction:'horizontal',
      dataId:'data2',
      yField: 'x',
      xField: 'y',
            line:{
        style:{
          lineDash:[2,5]
        }
      },

      point:{
        style:{
          symbolType:'rect',
          size:10,
          scaleX:1,
          scaleY:10,
        }
      }
    }
  ],
  axes: [
    {
      orient: 'left',
      seriesId:['barSeries','lineSeries'],
      type: 'band',
      grid: {
        visible: true
      }
    },
    {
      orient: 'top',
      type: 'linear',
      max:1.2,
      seriesId:['barSeries'],
      grid: {
        visible: true
      },
      visible:false
    },
        {
      orient: 'bottom',
      type: 'linear',
      seriesId:['lineSeries'],

      grid: {
        visible: true
      },
    }
  ],
}
```

## 结果展示 Results

在线效果参考：https://codesandbox.io/s/bar-chart-and-tgi-chart-8fkprk?file=/src/index.ts

Online demo：https://codesandbox.io/s/bar-chart-and-tgi-chart-8fkprk?file=/src/index.ts
![image](https://github.com/VisActor/VChart/assets/2384516/2c16b783-8ca8-454b-bef2-67d7d7b20b3e)


## 相关文档 Related Documentation

VChart组合图教程：https://visactor.bytedance.net/vchart/guide/tutorial_docs/Chart_Types/Combination

组合图配置项：https://visactor.bytedance.net/vchart/option/commonChart#type

github：https://github.com/VisActor/VChart

  


VChart Combination Chart Tutorial：https://visactor.bytedance.net/vchart/guide/tutorial_docs/Chart_Types/Combination

Related api：https://visactor.bytedance.net/vchart/option/commonChart#type

github：https://github.com/VisActor/VChart
